### PR TITLE
Graph Coloring based register allocator.

### PR DESCRIPTION
**Pull request by M4GNV5**
This pull request contains all commits done during my Google Summer of Code project. It implements a graph coloring based register allocator.

For more information please read my [Work Product Submission](https://github.com/M4GNV5/GSoC2018/blob/master/README.md)

### CODE REVIEW

**Comment by M4GNV5** [comment]
I'm continuing development of the register allocator in a new branch [post-gsoc](https://github.com/M4GNV5/libjit/tree/post-gsoc), so the gsoc branch only contains stuff i did during GSoC.
Im closing this PR and opening another one later when the missing things are implemented, tested and the new commits from upstream are merged :)

**Comment by tromey** [comment]
What is the status of this?  I tried the post-gsoc branch on a test case I was looking at (https://lists.gnu.org/archive/html/libjit/2018-02/msg00011.html) and it is much better ... what remains to be done on that branch?

**Comment by ademakov** [comment]
The patch is huge and I suspect there is a big chance that it would destabilize libjit, it would be easier for me to integrate it if it was split to smaller pieces.

**Comment by M4GNV5** [comment]
Yes, the main problem is that the patch might have unfound bugs.
I fixed some bugs i found with the unit tests of my toy language and found some time during 36c3 to fix some more bugs i found with the dpas tests in libjit. Maybe we can compare the emacs lisp tests with and without the new regalloc to check if there are any bugs left? This should give us enough confidence that the patch is safe regardless of its size.

**Pull request closed without merging**
